// Define the type for specification items
export interface SpecItem {
    category: string;
    detail: string;
  }
  
  // Border Fence Specifications Component
  // This component contains all the technical specifications for each part of the border fence
  export const BorderFenceSpecs: Record<string, SpecItem[]> = {
    "WELD MESH PANEL": [
      { category: "Panel size", detail: "2667 mm X 955 mm (W x H), Tolerance of ± 2 %." },
      { category: "Mesh Size", detail: "76.2 mm ± 3 mm X 12.7 mm ± 2 mm (W X H)." },
      { category: "Weld Shear strength", detail: "The average weld shear strength of 4 welds taken at random shall not be less than 50% of the breaking strength of the smallest wire (in this case the vertical wire)." },
      { category: "Mesh Wire", detail: "Galvanized MS wire conforming to requirements of IS 280-2006 as well as IS:7887. Wire diameter 4.0 mm (± 0.05mm)." },
      { category: "Tensile Strength of wire", detail: "Min 550 N/sq.mm." },
      { category: "V-Shape notch", detail: "2 nos. per panel of depth 38 mm and width 107 mm and 100° angle." },
      { category: "Overlapping of panels", detail: "75 mm overlap in horizontal direction and 167 mm overlap in vertical directions." },
      { category: "Panel weight", detail: "24.30Kgs (± 5 %)." },
      { category: "Galvanizing of wire", detail: "Hot dip galvanized coating, done as per IS:2629, shall have minimum mass of 60/100 GSM, as determined as per IS:6745. The coating shall conform to IS 4826." },
      { category: "Coating", detail: "Depending upon the corrosion rating C4 or C5 of the environment, the panels can be coated in two different ways for C4 environment Dual powder coating is recommended and for C5 environment Thermoplastic coating is recommended." },
      { category: "Dual Powder coating", detail: "The panels are dual coated with base coat of a primer powder and top coat with polyester powder with thickness of minimum120 μm for C4." },
      { category: "Thermoplastic coating", detail: "The panels are thermoplastic powder coated after fabrication on galvanized base with a minimum thickness of 300 μm for C5." },
      { category: "Corrosion Coating Standard", detail: "EN 10245-1." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "1200 Pieces, the quantity suggested are based on flat ground." },
    ],
    "FENCE (CHS) POST": [
      { category: "Type", detail: "Circular Hollow Section, Specification – IS:1161 -2014 (Medium Grade, Yst - 210MPa/ 240MPa)." },
      { category: "Outer Diameter", detail: "76.1 mm ±1%." },
      { category: "Thickness", detail: "3.60 mm / 4.0 mm ±10%." },
      { category: "Length", detail: "3400 mm ± 2%." },
      { category: "Base coating", detail: "Hot dip galvanized coating, done as per IS:2629, having minimum mass of 360 GSM, as determined as per IS:6745. The coating conforms to IS 4736." },
      { category: "Coating", detail: "Thermoplastic Powder Coating on galvanized base after fabrication of minimum thickness of 250 μm for C4 / 400 μm for C5." },
      { category: "Corrosion Coating Standards", detail: "IS 13871." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "400 Pieces, the quantity suggested are based on flat ground." },
    ],
    "ANCHOR ROD": [
      { category: "Material", detail: "MS Galvanized round bar." },
      { category: "Diameter", detail: "10mm." },
      { category: "Length", detail: "250mm / 300mm as per pit size." },
      { category: "Quantity per KM", detail: "802 Pieces." },
    ],
    "STRUT (CHS) POST": [
      { category: "Type", detail: "Circular Hollow Section, Specification – IS:1161 -2014 (Medium Grade, Yst - 210MPa/ 240MPa)." },
      { category: "Outer Diameter", detail: "76.1 mm ±1%." },
      { category: "Thickness", detail: "3.60 mm / 4.0 mm ±10%." },
      { category: "Length", detail: "3400 mm ± 2%." },
      { category: "Base coating", detail: "Hot dip galvanized coating, done as per IS:2629, having minimum mass of 360 GSM, as determined as per IS:6745. The coating conforms to IS 4736." },
      { category: "Coating", detail: "Thermoplastic Powder Coating on galvanized base after fabrication of minimum thickness of 250 μm for C4 / 400 μm for C5." },
      { category: "Corrosion Coating Standards", detail: "IS 13871." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "2 Pieces, the quantity suggested are based on flat ground." },
    ],
    "OMEGA CLAMP WITH PROFILE COVER PLATE": [
      { category: "Omega Clamp", detail: "178 mm X 35 mm, MS flat 35 mm width and 3.0 mm thick, as per IS 1730." },
      { category: "Profile Cover Plate", detail: "178 mm X 50.20 mm, MS flat 3.0 mm thick, as per IS 1730." },
      { category: "Weight", detail: "Combined weight of Omega Clamp with profile cover plate is 0.60 Kg ±8%." },
      { category: "Galvanizing", detail: "Hot dip galvanized coating, done as per IS:2629, having minimum mass of 360 GSM, as determined as per IS:6745. The coating conforms to IS 4759." },
      { category: "Coating", detail: "Thermoplastic Powder Coating on galvanized base after fabrication of minimum thickness of 250 μm for C4 / 400 μm for C5." },
      { category: "Corrosion Coating Standard", detail: "IS 13871." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "2800 Pieces." },
    ],
    "INTERMEDIATE PANEL (IP) BINDER": [
      { category: "Material", detail: "M.S. Flat of size 25 x 3/5 mm, 160 mm long, with 2-slots as per IS 1730." },
      { category: "Weight", detail: "0.2 Kg ± 10%." },
      { category: "Galvanizing Coating", detail: "Hot dip galvanized coating, done as per IS:2629, having minimum mass of 360 GSM, as determined as per IS:6745. The coating conforms to IS 4759." },
      { category: "Coating", detail: "Thermoplastic Powder Coating on galvanized base after fabrication of minimum thickness of 250 μm for C4 / 400 μm for C5." },
      { category: "Corrosion Coating Standards", detail: "IS 13871." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "3200 Pieces / 1600 set." },
    ],
    "CORNER CLAMP": [
      { category: "Corner Clamp", detail: "132 mm X 132 mm long L shape, MS flat 35 mm width and 3.0 mm thick, as per IS 1730." },
      { category: "W clamp", detail: "150 mm / 110 w shape as per drawing, MS flat 3.0 mm thick, as per IS 1730." },
      { category: "Cody clamp", detail: "54 mm X32.5 mm, MS flat 3.0 mm thick, as per IS 1730." },
      { category: "Weight", detail: "Combined weight of corner clamp with w clamp and two clamps is 0.40 Kg ±8%." },
      { category: "Galvanizing", detail: "Hot dip galvanized coating, done as per IS:2629, having minimum mass of 360 GSM, as determined as per IS:6745. The coating conforms to IS 4759." },
      { category: "Coating", detail: "Thermoplastic Powder Coating on galvanized base after fabrication of minimum thickness of 250 μm for C4 / 400 μm for C5." },
      { category: "Corrosion Coating Standards", detail: "IS 13871." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "As per customer requirement." },
    ],
    "STRAINING Y ARM": [
      { category: "Material", detail: "MS Angle Size – 50mm x 50mm x 5mm as per IS 2062-2011 (Yst – 210 MPa)." },
      { category: "Sleeve Cap", detail: "Top Plate 90 mm diameter, 5 mm thick, welded to 2.90 mm thick 60.30 mm OD and 100 mm long M.S. pipe, having two sets of 14 mm diameter holes to fix mushroom nuts." },
      { category: "Weight", detail: "5.11 Kgs ± 8%." },
      { category: "Length", detail: "One Arm is 510 mm, angle of Y (between two arms can be) 90 / 120° degree." },
      { category: "Base Coating", detail: "Hot dip galvanized coating, done as per IS:2629, having minimum mass of 360 GSM, as determined as per IS:6745. The coating conforms to IS 4759." },
      { category: "Coating", detail: "Thermoplastic Powder Coating on galvanized base after fabrication of minimum thickness of 250 μm for C4 / 400 μm for C5." },
      { category: "Corrosion Coating Standards", detail: "IS:13871." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "35 Pieces." },
    ],
    "INTERMEDIATE Y-ARM": [
      { category: "Material", detail: "MS Angle Size :50 mm x 50 mm x 5 mm / 40 mm x 40 mm x 4mm as per IS 2062-2011 (Yst – 210 MPa)." },
      { category: "Sleeve Cap", detail: "Top plate - 2/3 mm thick MS Plate, 90 mm dia. Sleeve of 45 mm long pipe of 88.90 mm OD & 3.00 mm thick having two sets of 12 mm holes." },
      { category: "Weight", detail: "3.09(40 mm x 40 mm x 4mm )/5.00 (50 mm x 50 mm x 5 mm) Kgs ± 8%" },
      { category: "Length", detail: "One Arm is 510 mm, angle of Y (between two arms can be) 90 / 120° degree." },
      { category: "Base Coating", detail: "Hot dip galvanized coating, done as per IS:2629, shall have minimum mass of 360 GSM, as determined as per IS:6745. The coating conforms to IS 4759." },
      { category: "Coating", detail: "Thermoplastic Powder Coating on galvanized base after fabrication of minimum thickness of 250 μm for C4 / 400 μm for C5." },
      { category: "Corrosion Coating Standards", detail: "IS 13871" },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "365 Pieces" },
    ],
    "EYE BOLT": [
      { category: "Material", detail: "SS304 for C4 and SS 316 for C5." },
      { category: "Size", detail: "M8 X 100 mm." },
      { category: "Weight", detail: "Eye bolt, Nut and washer 0.10 Kg ± 10 %." },
      { category: "Quantity per KM", detail: "210 Pieces." },
    ],
    "PTCC PUNCHED TAPE CONCERTINA COIL": [
      { category: "Concertina Coil", detail: "850 mm dia/ 56 loops/ 3.5mm core wire." },
      { category: "Coil Diameter", detail: "850 mm ± 50 mm." },
      { category: "Weight of coil", detail: "20.01 Kg (± 5%)." },
      { category: "Steel Tape Dimensions", detail: "Steel Tape material SS304 for C4 / SS 316 for C5 conforming to IS 6911." },
      { category: "Blade Thickness", detail: "0.45 mm ± 0.02 mm." },
      { category: "Blade Length", detail: "30 mm." },
      { category: "Blade Profile", detail: "Medium Blade (TBBT), Centre to Centre distance between blades 50 mm." },
      { category: "Material of Clip", detail: "SS304 for C4 / SS 316 for C5." },
      { category: "Core Wire Diameter", detail: "3.5 mm ± 0.05 mm as per IS:6528." },
      { category: "Tensile Strength of wire", detail: "1400 to 1500 N/sq.mm." },
      { category: "Core Wire", detail: "SS304 for C4 / SS 316 for C5." },
      { category: "Quantity per KM", detail: "100 Coils." },
    ],
    "RAZOR WIRE TAPE": [
      { category: "Weight of roll", detail: "13.20 Kg (± 5%)." },
      { category: "Steel Tape Dimensions", detail: "0.2 Kg ± 10%." },
      { category: "Blade Thickness", detail: "0.45 mm ± 0.02 mm." },
      { category: "Blade Length", detail: "30 mm." },
      { category: "Blade Profile", detail: "Medium Blade (TBBT), Centre to Centre distance between blades 50 mm." },
      { category: "Material of Clip", detail: "SS304 for C4 / SS 316 for C5." },
      { category: "Core Wire Diameter", detail: "3.5 mm ± 0.05 mm as per IS:6528." },
      { category: "Tensile Strength of wire", detail: "1400 to 1500 N/sq.mm." },
      { category: "Core Wire", detail: "SS304 for C4 / SS 316 for C5." },
      { category: "Quantity per KM", detail: "63 Bundle." },
    ],
    "TIE WIRE FOR RAZOR TAPE": [
      { category: "Weight of roll", detail: "8.8 gram per meter." },
      { category: "Wire Diameter", detail: "1.2mm." },
      { category: "Steel Grade", detail: "SS304 for C4 / SS316 for C5." },
      { category: "Length used per Y", detail: "2 meters." },
      { category: "Quantity per KM", detail: "70 meters (0.62Kg)." },
    ],
    "M8X120MM MUSHROOM HEAD BOLT, NUT & WASHER": [
      { category: "Material", detail: "SS304 for C4/ SS 316 for C5." },
      { category: "Size", detail: "M8 X 120 mm." },
      { category: "Weight", detail: "Bolt, Nut & Washer 0.050 Kg ± 8 %." },
      { category: "Quantity per KM", detail: "800 Set." },
    ],
    "M8X75MM MUSHROOM HEAD BOLT, NUT & WASHER": [
      { category: "Material", detail: "SS304 for C4/ SS 316 for C5." },
      { category: "Size", detail: "M8 X 75 mm." },
      { category: "Weight", detail: "Bolt, Nut & Washer 0.035 Kg ± 8 %." },
      { category: "Quantity per KM", detail: "1600 Set." },
    ],
    "M8X60MM MUSHROOM HEAD BOLT, NUT & WASHER": [
      { category: "Material", detail: "SS304 for C4/ SS 316 for C5." },
      { category: "Size", detail: "M8 X 60 mm." },
      { category: "Weight", detail: "Bolt, Nut & Washer 0.031 Kg ± 8 %." },
      { category: "Quantity per KM", detail: "4000 Set." },
    ],
    "M8X35MM MUSHROOM HEAD BOLT, NUT & WASHER": [
      { category: "Material", detail: "SS304 for C4/ SS 316 for C5" },
      { category: "Size", detail: "M8 X 35 mm" },
      { category: "Weight", detail: "Bolt, Nut & Washer 0.025 Kg ± 8 %" },
      { category: "Quantity per KM", detail: "3200 Set" },
    ],
    "HOG RINGS": [
      { category: "Dimensions & Standards", detail: "To secure concertina coil and consecutive concertina coils." },
      { category: "Material", detail: "SS 304 for C4 / SS 316 for C5; Dia: 3 mm." },
      { category: "Quantity per KM", detail: "8000 Pieces." },
    ],
    // Default specifications for components without specific details
    "DEFAULT": [
      { category: "Galvanizing", detail: "Hot dip galvanized coating, done as per IS:2629, shall have minimum mass of 60/100 GSM, as determined as per IS:6745. The coating shall conform to IS 4826." },
      { category: "Coating", detail: "Depending upon the corrosion rating C4 or C5 of the environment, the panels can be coated in two different ways for C4 environment Dual powder coating is recommended and for C5 environment Thermoplastic coating is recommended." },
      { category: "Dual Powder coating", detail: "The panels are dual coated with base coat of a primer powder and top coat with polyester powder with thickness of minimum120 μm for C4." },
      { category: "Thermoplastic coating", detail: "The panels are thermoplastic powder coated after fabrication on galvanized base with a minimum thickness of 300 μm for C5." },
      { category: "Corrosion Coating Standard", detail: "EN 10245-1." },
      { category: "Color", detail: "RAL 6005." },
      { category: "Quantity per KM", detail: "Varies based on component and terrain requirements." },
    ]
  }; 